server:
  port: ${PORT:8080}
spring:
  datasource:
    auto-commit: false
    driver-class-name: org.postgresql.Driver
    password: ${JDBC_PASSWORD}
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
  flyway:
    out-of-order: true
    table: "cryptosense_schema_history"
    schemas: ${DB_SCHEMA:cryptosense}
  jpa:
    properties:
      hibernate.default_schema: ${DB_SCHEMA:cryptosense}

management:
  endpoints:
    web:
      base-path: '/'
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true