server:
  port: ${PORT:8091}
spring:
  datasource:
    auto-commit: false
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/czertainly?characterEncoding=UTF-8'
    username: 'postgres'
    password: 'root'

  flyway:
    out-of-order: true
    table: "cryptosense_schema_history"
    schemas: ${DB_SCHEMA:cryptosense}
  jpa:
    properties:
      hibernate.default_schema: ${DB_SCHEMA:cryptosense}